# Generated by Django 4.0.6 on 2022-09-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masdatosusuario',
            name='description',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
