# Generated by Django 4.1.1 on 2022-09-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masdatosusuario',
            name='description',
            field=models.CharField(default='usuario', max_length=50),
            preserve_default=False,
        ),
    ]
