<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-07-07 00:42
=======
# Generated by Django 4.0.6 on 2022-07-06 23:57
>>>>>>> 4582a38a0d9a8ce36bdc998370dc899340a0f8c7

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('genero', models.CharField(max_length=250)),
                ('anios_activa', models.IntegerField()),
            ],
        ),
    ]
