# Generated by Django 4.1.1 on 2022-09-06 16:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('genero', models.CharField(max_length=250)),
                ('critica', ckeditor.fields.RichTextField()),
                ('publicacion', models.ImageField(blank=True, null=True, upload_to='posteos')),
                ('fecha_del_post', models.DateField(null=True)),
            ],
        ),
    ]
