# Generated by Django 4.0.6 on 2022-09-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='critica',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
