# Generated by Django 4.1.1 on 2022-09-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
