# Generated by Django 4.1.1 on 2022-09-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_banda_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='fecha_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
