# Generated by Django 4.0.6 on 2022-09-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_banda_critica'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='fecha_del_post',
            field=models.DateField(null=True),
        ),
    ]
