# Generated by Django 4.0.6 on 2022-09-05 21:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_banda_fecha_del_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banda',
            old_name='anios_activa',
            new_name='fecha_de_formacion',
        ),
        migrations.AlterField(
            model_name='banda',
            name='critica',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.CreateModel(
            name='MasDatosPosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ImageField(blank=True, null=True, upload_to='posteos')),
                ('banda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bandas.banda')),
            ],
        ),
    ]
