# Generated by Django 4.0.6 on 2022-09-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_banda_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banda',
            old_name='anios_activa',
            new_name='fecha_de_formacion',
        ),
    ]
