# Generated by Django 4.0.6 on 2022-09-06 00:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_rename_anios_activa_banda_fecha_de_formacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='critica',
            field=ckeditor.fields.RichTextField(default='nothing'),
            preserve_default=False,
        ),
    ]
