# Generated by Django 4.0.6 on 2022-09-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_rename_anios_activa_banda_fecha_de_formacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='banda',
            name='imagen',
        ),
        migrations.AddField(
            model_name='banda',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
