# Generated by Django 4.0.6 on 2022-09-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_imagen_remove_banda_imagen_banda_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to='posteos'),
        ),
    ]
