# Generated by Django 4.0.6 on 2022-08-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagepost')),
            ],
        ),
    ]
